{{- if and .Values.azure .Values.azure.enabled }}
---
# Azure credentials Secret used by ProviderConfig
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.azure.providerConfigName }}
  namespace: {{ .Values.azure.secretNamespace | default .Release.Namespace }}
type: Opaque
stringData:
  credentials: |
    {
      "clientId": "{{ .Values.azure.credentials.clientId }}",
      "clientSecret": "{{ .Values.azure.credentials.clientSecret }}",
      "tenantId": "{{ .Values.azure.credentials.tenantId }}",
      "subscriptionId": "{{ .Values.azure.credentials.subscriptionId }}"
    }
---
# Azure ProviderConfig (cluster-scoped)
apiVersion: azure.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: {{ .Values.azure.providerConfigName }}
spec:
  credentials:
    source: Secret
    secretRef:
      name: {{ .Values.azure.providerConfigName }}
      namespace: {{ .Values.azure.secretNamespace | default .Release.Namespace }}
      key: credentials
{{- end }}


