{{- if and .Values.azure .Values.azure.enabled .Values.azure.aks.enabled }}
---
apiVersion: containerservice.azure.upbound.io/v1beta2
kind: KubernetesCluster
metadata:
  name: {{ .Values.azure.aks.clusterName }}
spec:
  forProvider:
    location: {{ .Values.azure.location }}
    resourceGroupName: {{ .Values.azure.resourceGroup.name }}
    dnsPrefix: {{ .Values.azure.aks.dnsPrefix }}
    kubernetesVersion: {{ (.Values.azure.aks.kubernetesVersion | default "1.32.6") | quote }}
    identity:
      type: "SystemAssigned"
    defaultNodePool:
      name: {{ .Values.azure.aks.nodePool.name | default "default" }}
      nodeCount: {{ .Values.azure.aks.nodePool.nodeCount | default 1 }}
      vmSize: {{ .Values.azure.aks.nodePool.vmSize | default "Standard_D2s_v3" }}
      vnetSubnetIdRef:
        name: {{ .Values.azure.vnet.subnet.subnetName | default .Values.azure.vnet.subnetName }}
      type: VirtualMachineScaleSets
    networkProfile:
      networkPlugin: azure
      serviceCidr: {{ (.Values.azure.aks.networkProfile.serviceCidr | default "10.1.0.0/16") | quote }}
      dnsServiceIp: {{ (.Values.azure.aks.networkProfile.dnsServiceIp | default "10.1.0.10") | quote }}
  providerConfigRef:
    name: {{ .Values.azure.providerConfigName }}
{{- end }}