{{- if and .Values.azure .Values.azure.enabled .Values.azure.storage.enabled }}
---
apiVersion: storage.azure.upbound.io/v1beta1
kind: Account
metadata:
  name: {{ .Values.azure.storage.accountName }}
spec:
  forProvider:
    location: {{ .Values.azure.location }}
    resourceGroupName: {{ .Values.azure.resourceGroup.name }}
    accountTier: {{ .Values.azure.storage.accountTier | default "Standard" }}
    accountReplicationType: {{ .Values.azure.storage.accountReplicationType | default "LRS" }}
    accountKind: {{ .Values.azure.storage.accountKind | default "StorageV2" }}
  providerConfigRef:
    name: {{ .Values.azure.providerConfigName }}
---
apiVersion: storage.azure.upbound.io/v1beta1
kind: Container
metadata:
  name: {{ .Values.azure.storage.containerName }}
spec:
  forProvider:
    storageAccountName: {{ .Values.azure.storage.accountName }}
    containerAccessType: {{ .Values.azure.storage.containerAccessType | default "private" }}
  providerConfigRef:
    name: {{ .Values.azure.providerConfigName }}
{{- end }}


