azure:
  enabled: true
  location: eastus
  providerConfigName: azur-creds
  secretNamespace: crossplane-system
  credentials:
    clientId: ""
    clientSecret: ""
    tenantId: ""
    subscriptionId: "" 

  resourceGroup:
    enabled: true
    name: crossplane-regroup
  storage:
    enabled: true
    accountName: crossplanestorage6429148
    accountTier: Standard
    accountReplicationType: LRS
    accountKind: StorageV2
    containerName: crossplanecontainer838391
    containerAccessType: private
  vnet:
    enabled: true
    vnetName: crossplane-vnet
    addressSpace: "10.0.0.0/16"
    subnet:
      enabled: true
      subnetName: crossplane-subnet
      addressPrefix: "10.0.1.0/24"
  aks:
    enabled: true
    clusterName: crossplane-aks-cluster
    dnsPrefix: crossplane-aks-prefix
    kubernetesVersion: ""
    nodePool:
      name: default
      nodeCount: 1
      vmSize: "Standard_D2s_v3"
    networkProfile:
      serviceCidr: "10.1.0.0/16"
      dnsServiceIp: "10.1.0.10"
    
